contest/urls.py
from django.urls import path

from contest import views as v

app_name = "contest"
urlpatterns = [
    path("", v.index, name="index"),
    path("list/", v.contest_list, name="contest_list"),
    path("<int:contest_id>/", v.contest_view, name="contest_view"),
    path(
        "<int:contest_id>/participants/",
        v.participant_list,
        name="participant_list",
    ),
    path(
        "<int:contest_id>/participant/<int:participant_id>",
        v.participant_view,
        name="participant_view",
    ),
    path("vote/", v.vote, name="vote"),
]

imaginaria/urls.py
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path


from imaginaria import views as v

urlpatterns = [
    # path("", include("pwa.urls", namespace="pwa")),
]

urlpatterns += i18n_patterns(
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
    path("admin/", admin.site.urls),
    path("", v.index),
    path(
        "authentication/",
        include("authentication.urls", namespace="authentication"),
    ),
    path("contest/", include("contest.urls", namespace="contest")),
)


handler500 = "imaginaria.views.handler500"
handler404 = "imaginaria.views.handler404"
handler403 = "imaginaria.views.handler403"
handler400 = "imaginaria.views.handler400"

pwa/urls.py
from django.urls import path

from .views import manifest, service_worker, offline


app_name = "pwa"
urlpatterns = [
    path("serviceworker.js", service_worker, name="serviceworker"),
    path("manifest.json", manifest, name="manifest"),
    path("offline", offline, name="offline"),
]

contest/models.py
from authentication.models import User
from django.db.models import Q
from django.db import models
from django.db.models.signals import pre_save
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator


class Contest(models.Model):
    name = models.CharField(
        _("name"), null=False, blank=False, unique=True, max_length=255
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
    )
    start_date = models.DateTimeField(_("início"), default=now)
    end_date = models.DateTimeField(
        _("término"),
    )
    judges = models.ManyToManyField(
        User, blank=True, verbose_name="jurados", related_name="judges"
    )
    judge_vote_weight = models.IntegerField(
        _("peso do voto dos jurados"),
        help_text=_(
            'Exemplo: se especificado "3" e o jurado votar "5", o voto será computado como 15.'
        ),
        null=False,
        blank=False,
        validators=[MinValueValidator(1)],
        default=1,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
        editable=False,
    )
    created_date = models.DateTimeField(_("created date"), auto_now_add=True)

    class Meta:
        verbose_name = _("concurso")
        verbose_name_plural = _("concursos")

    def __str__(self):
        return self.name


class Participant(models.Model):
    name = models.CharField(_("nome"), null=False, blank=False, max_length=255)
    work = models.CharField(_("trabalho"), null=False, blank=False, max_length=255)
    description = models.TextField(_("descrição"), null=True, blank=True)
    video_url = models.URLField(_("URL do vídeo"), null=False, blank=False)
    contest = models.ForeignKey(
        Contest,
        verbose_name="concurso",
        on_delete=models.CASCADE,
        null=False,
        limit_choices_to=Q(is_active=True) & Q(end_date__gt=now()),
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
        editable=False,
    )
    created_date = models.DateTimeField(_("created date"), auto_now_add=True)

    class Meta:
        verbose_name = _("participante")
        verbose_name_plural = _("participantes")
        unique_together = ("name", "contest")

    def __str__(self):
        return self.name


class Vote(models.Model):
    vote = models.IntegerField(validators=[MinValueValidator(1)], default=0)
    registered_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
    )
    participant = models.ForeignKey(
        Participant,
        on_delete=models.CASCADE,
        null=False,
    )
    created_date = models.DateTimeField(
        _("created date"), auto_now_add=True, editable=False
    )

    class Meta:
        verbose_name = _("voto")
        verbose_name_plural = _("votos")
        unique_together = ("registered_by", "participant")


def check_vote(sender, instance, *args, **kwargs):
    vote = int(instance.vote)
    if vote > 5:
        raise ValueError(_("O voto máximo é 5"))

    if (
        instance.participant.contest.start_date >= now()
        or instance.participant.contest.end_date <= now()
    ):
        raise ValueError(_("Só é possível votar em concursos em andamento"))


def check_dates(sender, instance, *args, **kwargs):
    if instance.start_date > instance.end_date:
        raise ValueError(_("Data de término deve ser maior que a data de início."))


pre_save.connect(check_vote, sender=Vote)
pre_save.connect(check_dates, sender=Contest)

contest/views.py
import time

from authentication.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import (
    F,
    Prefetch,
    Q,
    Sum,
    ExpressionWrapper,
    IntegerField,
    Case,
    When,
)
from django.db.models.functions import Coalesce
from django.shortcuts import render
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from contest.models import Contest, Participant, Vote


def index(request):
    context = {}

    present_contests = Contest.objects.filter(
        start_date__lt=now(), end_date__gt=now(), is_active=True
    ).prefetch_related(
        Prefetch(
            "participant_set",
            queryset=Participant.objects.annotate(
                rating_sum=Coalesce(Sum("vote__vote"), 0)
            ),
        )
    )
    context["present_contests"] = present_contests

    future_contests = Contest.objects.filter(start_date__gt=now(), is_active=True)
    context["future_contests"] = future_contests

    past_contests = Contest.objects.filter(
        end_date__lt=now(), is_active=True
    ).prefetch_related(
        Prefetch(
            "participant_set",
            queryset=Participant.objects.annotate(
                rating_sum=Coalesce(Sum("vote__vote"), 0)
            ),
        )
    )
    context["past_contests"] = past_contests

    return render(request, "contest/index.html", context=context)


@login_required
def contest_list(request):
    context = {}

    contests = Contest.objects.filter(
        start_date__lt=now(), end_date__gt=now(), is_active=True
    )
    context["contests"] = contests

    participants = (
        Participant.objects.filter(contest__in=contests)
        .annotate(rating_sum=Coalesce(Sum("vote__vote"), 0))
        .order_by("-rating_sum")
    )[:9]

    context["participants"] = participants

    return render(request, "contest/contest/list.html", context=context)


def contest_view(request, contest_id):
    context = {}

    contest = Contest.objects.filter(pk=contest_id)[0]
    context["contest"] = contest

    participants = (
        Participant.objects.filter(contest=contest)
        .annotate(rating_sum=Coalesce(Sum("vote__vote"), 0))
        .order_by("-rating_sum")
    )
    context["participants"] = participants

    return render(request, "contest/contest/view.html", context=context)


def participant_list(request, contest_id):
    context = {}

    page = request.GET.get("page", 1)

    user = None
    if request.user.is_authenticated:
        user = request.user

    contest = Contest.objects.get(pk=contest_id)
    context["contest"] = contest

    participants = (
        Participant.objects.filter(contest=contest)
        .annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch("vote_set", queryset=Vote.objects.filter(registered_by=user))
        )
        .order_by("name")
    )

    print(participants)

    if "search" in request.GET:
        participants = participants.filter(
            Q(name__icontains=request.GET.get("search"))
            | Q(work__icontains=request.GET.get("search"))
        )
        context["search"] = request.GET.get("search")

    context["pagination"] = request.GET.get("pagination", 6)
    participants = Paginator(participants, context["pagination"])
    participants_page = participants.page(page)
    context["participants"] = participants_page

    context["ongoing"] = (
        contest.start_date <= now() and contest.end_date >= now() and contest.is_active
    )

    return render(request, "contest/participant/list.html", context=context)


def participant_view(request, contest_id, participant_id):
    context = {}

    user = request.user if request.user.is_authenticated else None

    participant = (
        Participant.objects.annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch(
                "contest",
                queryset=Contest.objects.filter(id=contest_id),
            ),
        )
        .prefetch_related(
            Prefetch("vote_set", queryset=Vote.objects.filter(registered_by=user))
        )
        .get(pk=participant_id)
    )

    context["participant"] = participant
    context["pagination"] = "1"
    context["ongoing"] = (
        participant.contest.start_date <= now()
        and participant.contest.end_date >= now()
        and participant.contest.is_active
    )

    return render(request, "contest/participant/view.html", context=context)


@login_required
def vote(request):
    context = {}

    vote, created = Vote.objects.update_or_create(
        registered_by=request.user,
        participant_id=request.POST.get("participant_id"),
        defaults={"vote": request.POST.get("vote")},
    )

    participant = (
        Participant.objects.annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch(
                "vote_set",
                queryset=Vote.objects.filter(
                    registered_by=request.user,
                    participant__id=request.POST.get("participant_id"),
                ),
            )
        )
        .get(pk=request.POST.get("participant_id"))
    )
    context["participant"] = participant

    context["ongoing"] = (
        participant.contest.start_date <= now()
        and participant.contest.end_date >= now()
        and participant.contest.is_active
    )

    time.sleep(1)

    return render(request, "contest/participant/_participant.html", context)

contest/templates/contest/participant/_participant.html
{% load static %}
{% load i18n %}

<div class="video-container">
    <div class="video">
        <iframe src="{{ participant.video_url }}" scrolling="no"></iframe>
    </div>
</div>
<div class="participant-votes_received">
    <b>{{ participant.rating }}</b>
    <img height="20px" src="{% static "imaginaria/images/LovelyHouse_empty.png" %}">
</div>
<a href="{% url "contest:participant_view" contest_id=participant.contest.id participant_id=participant.id %}" target="_blank" class="participant-work">
    {{ participant.work }} 
</a>
<br />
<span class="participant-name">{{ participant.name }}</span>
<br />
{% if participant.description %}
    {% autoescape off %}
        {% if pagination == "1" %}
        <div style="margin-top: 10px;">
            {{ participant.description }}
        </div>
        {% else %}
            <details class="participant-description">
                <summary>{% translate "Descrição" %}</summary>
                <p>{{ participant.description }}</p>
            </details>
        {% endif %}
    {% endautoescape %}
{% endif %}
{% if ongoing %}
    {% if participant.vote_set %}
        <div id="vote_{{ participant.id }}" class="vote" onmouseout="vote({{ participant.id }}, {{ participant.vote_set.get.vote|slugify }})">
            {% for r in "54321" %}
                <img
                    id="vote_{{ participant.id }}_{{ r }}"
                    name="{{ participant.id }}_{{ r }}"
                    onmouseover="vote({{ participant.id }}, {{ r }})" height="20px"
                    src="{% if r <= participant.vote_set.get.vote|slugify %}
                            {% static "imaginaria/images/LovelyHouse_filled.png" %}
                        {% else %}
                            {% static "imaginaria/images/LovelyHouse_empty.png" %}
                        {% endif %}"
                    hx-post="{% url "contest:vote" %}"
                    hx-trigger="click[is_authenticated({{ user.is_authenticated|slugify }}, gettext('Você precisa estar logado para votar'))]"
                    hx-target="#participant-container_{{ participant.id }}"
                    hx-vals='{"participant_id": {{ participant.id }}, "vote": {{ r }}}'
                    hx-indicator="#loading"
                    >
            {% endfor %}
        </div>    
    {% endif %}
{% endif %}

contest/templates/contest/participant/list.html
{% extends "imaginaria/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <title>{{ contest.name }}</title>
    <link href="{% static "contest/css/participant/list.css" %}" rel="stylesheet" />
    <link href="{% static "contest/css/participant/_participant.css" %}" rel="stylesheet" />
    <script type="text/javascript" src="{% static "contest/js/participant/_participant.js" %}"></script>
{% endblock head %}

{% block content %}
    <div class="contest">
        <div class="view-type">
            <a href="?search={{ search }}" class="selected">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h13A1.5 1.5 0 0 1 16 3.5v8a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 11.5v-8zM1.5 3a.5.5 0 0 0-.5.5V7h4V3H1.5zM5 8H1v3.5a.5.5 0 0 0 .5.5H5V8zm1 0v4h4V8H6zm4-1V3H6v4h4zm1 1v4h3.5a.5.5 0 0 0 .5-.5V8h-4zm0-1h4V3.5a.5.5 0 0 0-.5-.5H11v4z"/>
                </svg>
            </a>
            <a href="?search={{ search }}&pagination=4" class="selected">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
                </svg>
            </a>
            <a href="?search={{ search }}&pagination=1" class="selected">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                </svg>
            </a>
        </div>
        <header class="contest-name">
            <a href="{% url "contest:participant_list" contest_id=contest.id %}">{{ contest.name }}</a>
            <br />
            <span class="contest-date"><b>{% translate "Início" %}:</b> {{ contest.start_date }}</span>
            <br />
            <span class="contest-date"><b>{% translate "Fim" %}:</b> {{ contest.end_date }}</span>
        </header>
        <form class="search" method="GET" action="{% url "contest:participant_list" contest_id=contest.id %}">
            {% csrf_token %}
            <input name="search" type="text" placeholder="{% translate "Pesquisar" %}" value="{{ search }}">
            <input type="submit" value="_{% translate "ir" %}">
            {% if search %}
                <input type="button" value="_{% translate "limpar" %}" onclick="window.location.replace(location.pathname);">
            {% endif %}
        </form>
        <hr style="border-top: 2px solid var(--complementary-color); margin-top: 10px">
        <div id="participant-grid">
            {% for participant in participants %}
                <div id="participant-container_{{ participant.id }}" class="participant {% if pagination == "1" %}featured {% elif pagination == "4" %}quatro{% endif %}">
                    {% include "contest/participant/_participant.html" %}
                </div>
            {% endfor %}
        </div>
        {% if participants.has_other_pages %}
            <ul class="pagination">
                {% if participants.has_previous %}
                    <li>
                        <a href="?search={{ search }}&pagination={{ pagination }}&page={{ participants.previous_page_number }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 -3 16 16">
                                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                            </svg>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 -3 16 16">
                            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                        </svg>
                    </li>
                {% endif %}
                {% for i in participants.paginator.page_range %}
                    {% if participants.number == i %}
                        <li class="active"><span>{{ i }}</span></li>
                    {% else %}
                        <li><a href="?search={{ search }}&pagination={{ pagination }}&page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if participants.has_next %}
                    <li>
                        <a href="?search={{ search }}&pagination={{ pagination }}&page={{ participants.next_page_number }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 -3 16 16">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                            </svg>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 -3 16 16">
                            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                        </svg>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock content %}

contest/templates/contest/participant/view.html
{% extends "imaginaria/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <link href="{% static "contest/css/participant/view.css" %}" rel="stylesheet" />
    <link href="{% static "contest/css/participant/_participant.css" %}" rel="stylesheet" />
    <script type="text/javascript" src="{% static "contest/js/participant/_participant.js" %}"></script>
{% endblock head %}

{% block content %}
    <header class="contest-name">
        <a href="{% url "contest:participant_list" contest_id=participant.contest.id %}">{{ participant.contest.name }}</a>
        <br />
        <span class="contest-date"><b>{% translate "Início" %}:</b> {{ participant.contest.start_date }}</span>
        <br />
        <span class="contest-date"><b>{% translate "Fim" %}:</b> {{ participant.contest.end_date }}</span>
    </header>
    <div class="participant-wrapper">
        <div id="participant-container_{{ participant.id }}" class="participant featured">
            {% include "contest/participant/_participant.html" %}
        </div>
    </div>
{% endblock content %}