authentication/urls.py
from django.urls import path

from authentication import views as v

app_name = "authentication"
urlpatterns = [
    path("login/", v.login_view, name="login"),
    path("logout/", v.logout_view, name="logout"),
    path("register/", v.register_user, name="register_user"),
    path(
        "activate/<str:user_id_b64>/<str:token>/", v.activate_user, name="activate_user"
    ),
    path(
        "resend_activation_email/",
        v.resend_activation_email,
        name="resend_activation_email",
    ),
    path(
        "forgot-password/",
        v.send_forgot_password_mail,
        name="send_forgot_password_mail",
    ),
    path(
        "forgot-password/<user_id_b64>/<token>/",
        v.forgot_password_form,
        name="forgot_password_form",
    ),
]

contest/urls.py
from django.urls import path

from contest import views as v

app_name = "contest"
urlpatterns = [
    path("", v.index, name="index"),
    path("list/", v.contest_list, name="contest_list"),
    path("<int:contest_id>/", v.contest_view, name="contest_view"),
    path(
        "<int:contest_id>/participants/",
        v.participant_list,
        name="participant_list",
    ),
    path(
        "<int:contest_id>/participant/<int:participant_id>",
        v.participant_view,
        name="participant_view",
    ),
    path("vote/", v.vote, name="vote"),
]

imaginaria/urls.py
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path


from imaginaria import views as v

urlpatterns = [
    # path("", include("pwa.urls", namespace="pwa")),
]

urlpatterns += i18n_patterns(
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
    path("admin/", admin.site.urls),
    path("", v.index),
    path(
        "authentication/",
        include("authentication.urls", namespace="authentication"),
    ),
    path("contest/", include("contest.urls", namespace="contest")),
)


handler500 = "imaginaria.views.handler500"
handler404 = "imaginaria.views.handler404"
handler403 = "imaginaria.views.handler403"
handler400 = "imaginaria.views.handler400"

pwa/urls.py
from django.urls import path

from .views import manifest, service_worker, offline


app_name = "pwa"
urlpatterns = [
    path("serviceworker.js", service_worker, name="serviceworker"),
    path("manifest.json", manifest, name="manifest"),
    path("offline", offline, name="offline"),
]

imaginaria/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required


def index(request):
    return redirect("/contest/", permanent=True)


def handler500(request, exception=None):
    return render(
        request, "imaginaria/error.html", context={"exception": exception}, status=500
    )


def handler404(request, exception=None):
    return render(
        request, "imaginaria/error.html", context={"exception": exception}, status=404
    )


def handler403(request, exception=None):
    return render(
        request, "imaginaria/error.html", context={"exception": exception}, status=403
    )


def handler400(request, exception=None):
    return render(
        request, "imaginaria/error.html", context={"exception": exception}, status=400
    )

imaginaria/templates/imaginaria/base.html
{% load static %}
{% load i18n %}
{% comment %} {% load pwa %} {% endcomment %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
        <link rel="shortcut icon" type="image/png" href="{% static "imaginaria/images/favicon.png" %}" />
        <link href="{% static "imaginaria/css/root.css" %}" rel="stylesheet" />
        <link href="{% static "imaginaria/css/base.css" %}" rel="stylesheet" />
        {% comment %} {% progressive_web_app_meta %} {% endcomment %}
        <script src="{% static "imaginaria/js/htmx.min.js" %}"></script>
        <script src="{% url "javascript-catalog" %}"></script>
        <script>
            var static_url = "{% get_static_prefix %}";
            var media_url = "{% get_media_prefix %}";
        </script>
        <script type="text/javascript" src="{% static "imaginaria/js/base.js" %}"></script>
        {% block head %}{% endblock head %}
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <div id="loading" class="htmx-indicator">
            <div id="loading-wheel"></div>
        </div>

        <div id="navbar">
            <a href="/">
                <img src="{% static "imaginaria/images/logo.png" %}" />
            </a>
            <div id="navbar-items">
                
                <a id="website" href="https://festivalimaginaria.com.br/" target="_blank">_website</a>
                
                <a id="contests" href="{% url "contest:index" %}">_concursos</a>
                
                {% if user.is_staff %}
                <a id="admin" href="/admin" target="_blank">_administrador</a>
                {% endif %}
                
                {% if user.is_authenticated %}
                <a id="logout" href="{% url "authentication:logout" %}">_sair</a>
                {% else %}
                <a id="login" href="{% url "authentication:login" %}">_login</a>
                {% endif %}
                
            </div>
            <a id="delete_me" href="#">_deletar minha conta</a>
        </div>
        
        {% include "imaginaria/messages.html" %}
        <div id="content">
            {% block content %}{% endblock content %}
        </div>
    </body>
    </html>
    

imaginaria/templates/imaginaria/error.html
{% load static %}
<html>
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'imaginaria/images/favicon.png' %}"
    />
    <link href="{% static 'imaginaria/css/root.css' %}" rel="stylesheet" />
    <link href="{% static 'imaginaria/css/error.css' %}" rel="stylesheet" />
    <title>imaginaria: Erro</title>
  </head>
  <body>
    <img
      src="{% static 'imaginaria/images/sad_dog.png' %}"
      width="350px"
    />
    <p>
      Desculpe, um erro ocorreu.
      <br />
      <a href="/">Clique aqui</a> para voltar para a página inicial.
    </p>
    <details>{{ exception }}</details>
  </body>
</html>

imaginaria/templates/imaginaria/messages.html
{% if messages or form.errors %}
  <ul class="messages">
    {% for message in messages %}
      <li onclick="this.remove()" {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}