contest/urls.py
from django.urls import path

from contest import views as v

app_name = "contest"
urlpatterns = [
    path("", v.index, name="index"),
    path("list/", v.contest_list, name="contest_list"),
    path("<int:contest_id>/", v.contest_view, name="contest_view"),
    path(
        "<int:contest_id>/participants/",
        v.participant_list,
        name="participant_list",
    ),
    path(
        "<int:contest_id>/participant/<int:participant_id>",
        v.participant_view,
        name="participant_view",
    ),
    path("vote/", v.vote, name="vote"),
]

imaginaria/urls.py
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path


from imaginaria import views as v

urlpatterns = [
    # path("", include("pwa.urls", namespace="pwa")),
]

urlpatterns += i18n_patterns(
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
    path("admin/", admin.site.urls),
    path("", v.index),
    path(
        "authentication/",
        include("authentication.urls", namespace="authentication"),
    ),
    path("contest/", include("contest.urls", namespace="contest")),
)


handler500 = "imaginaria.views.handler500"
handler404 = "imaginaria.views.handler404"
handler403 = "imaginaria.views.handler403"
handler400 = "imaginaria.views.handler400"

pwa/urls.py
from django.urls import path

from .views import manifest, service_worker, offline


app_name = "pwa"
urlpatterns = [
    path("serviceworker.js", service_worker, name="serviceworker"),
    path("manifest.json", manifest, name="manifest"),
    path("offline", offline, name="offline"),
]

contest/models.py
from authentication.models import User
from django.db.models import Q
from django.db import models
from django.db.models.signals import pre_save
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator


class Contest(models.Model):
    name = models.CharField(
        _("name"), null=False, blank=False, unique=True, max_length=255
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
    )
    start_date = models.DateTimeField(_("início"), default=now)
    end_date = models.DateTimeField(
        _("término"),
    )
    judges = models.ManyToManyField(
        User, blank=True, verbose_name="jurados", related_name="judges"
    )
    judge_vote_weight = models.IntegerField(
        _("peso do voto dos jurados"),
        help_text=_(
            'Exemplo: se especificado "3" e o jurado votar "5", o voto será computado como 15.'
        ),
        null=False,
        blank=False,
        validators=[MinValueValidator(1)],
        default=1,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
        editable=False,
    )
    created_date = models.DateTimeField(_("created date"), auto_now_add=True)

    class Meta:
        verbose_name = _("concurso")
        verbose_name_plural = _("concursos")

    def __str__(self):
        return self.name


class Participant(models.Model):
    name = models.CharField(_("nome"), null=False, blank=False, max_length=255)
    work = models.CharField(_("trabalho"), null=False, blank=False, max_length=255)
    description = models.TextField(_("descrição"), null=True, blank=True)
    video_url = models.URLField(_("URL do vídeo"), null=False, blank=False)
    contest = models.ForeignKey(
        Contest,
        verbose_name="concurso",
        on_delete=models.CASCADE,
        null=False,
        limit_choices_to=Q(is_active=True) & Q(end_date__gt=now()),
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
        editable=False,
    )
    created_date = models.DateTimeField(_("created date"), auto_now_add=True)

    class Meta:
        verbose_name = _("participante")
        verbose_name_plural = _("participantes")
        unique_together = ("name", "contest")

    def __str__(self):
        return self.name


class Vote(models.Model):
    vote = models.IntegerField(validators=[MinValueValidator(1)], default=0)
    registered_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False,
    )
    participant = models.ForeignKey(
        Participant,
        on_delete=models.CASCADE,
        null=False,
    )
    created_date = models.DateTimeField(
        _("created date"), auto_now_add=True, editable=False
    )

    class Meta:
        verbose_name = _("voto")
        verbose_name_plural = _("votos")
        unique_together = ("registered_by", "participant")


def check_vote(sender, instance, *args, **kwargs):
    vote = int(instance.vote)
    if vote > 5:
        raise ValueError(_("O voto máximo é 5"))

    if (
        instance.participant.contest.start_date >= now()
        or instance.participant.contest.end_date <= now()
    ):
        raise ValueError(_("Só é possível votar em concursos em andamento"))


def check_dates(sender, instance, *args, **kwargs):
    if instance.start_date > instance.end_date:
        raise ValueError(_("Data de término deve ser maior que a data de início."))


pre_save.connect(check_vote, sender=Vote)
pre_save.connect(check_dates, sender=Contest)

contest/views.py
import time

from authentication.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import (
    F,
    Prefetch,
    Q,
    Sum,
    ExpressionWrapper,
    IntegerField,
    Case,
    When,
)
from django.db.models.functions import Coalesce
from django.shortcuts import render
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from contest.models import Contest, Participant, Vote


def index(request):
    context = {}

    present_contests = Contest.objects.filter(
        start_date__lt=now(), end_date__gt=now(), is_active=True
    ).prefetch_related(
        Prefetch(
            "participant_set",
            queryset=Participant.objects.annotate(
                rating_sum=Coalesce(Sum("vote__vote"), 0)
            ),
        )
    )
    context["present_contests"] = present_contests

    future_contests = Contest.objects.filter(start_date__gt=now(), is_active=True)
    context["future_contests"] = future_contests

    past_contests = Contest.objects.filter(
        end_date__lt=now(), is_active=True
    ).prefetch_related(
        Prefetch(
            "participant_set",
            queryset=Participant.objects.annotate(
                rating_sum=Coalesce(Sum("vote__vote"), 0)
            ),
        )
    )
    context["past_contests"] = past_contests

    return render(request, "contest/index.html", context=context)


@login_required
def contest_list(request):
    context = {}

    contests = Contest.objects.filter(
        start_date__lt=now(), end_date__gt=now(), is_active=True
    )
    context["contests"] = contests

    participants = (
        Participant.objects.filter(contest__in=contests)
        .annotate(rating_sum=Coalesce(Sum("vote__vote"), 0))
        .order_by("-rating_sum")
    )[:9]

    context["participants"] = participants

    return render(request, "contest/contest/list.html", context=context)


def contest_view(request, contest_id):
    context = {}

    contest = Contest.objects.filter(pk=contest_id)[0]
    context["contest"] = contest

    participants = (
        Participant.objects.filter(contest=contest)
        .annotate(rating_sum=Coalesce(Sum("vote__vote"), 0))
        .order_by("-rating_sum")
    )
    context["participants"] = participants

    return render(request, "contest/contest/view.html", context=context)


def participant_list(request, contest_id):
    context = {}

    page = request.GET.get("page", 1)

    user = None
    if request.user.is_authenticated:
        user = request.user

    contest = Contest.objects.get(pk=contest_id)
    context["contest"] = contest

    participants = (
        Participant.objects.filter(contest=contest)
        .annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch("vote_set", queryset=Vote.objects.filter(registered_by=user))
        )
        .order_by("name")
    )

    print(participants)

    if "search" in request.GET:
        participants = participants.filter(
            Q(name__icontains=request.GET.get("search"))
            | Q(work__icontains=request.GET.get("search"))
        )
        context["search"] = request.GET.get("search")

    context["pagination"] = request.GET.get("pagination", 6)
    participants = Paginator(participants, context["pagination"])
    participants_page = participants.page(page)
    context["participants"] = participants_page

    context["ongoing"] = (
        contest.start_date <= now() and contest.end_date >= now() and contest.is_active
    )

    return render(request, "contest/participant/list.html", context=context)


def participant_view(request, contest_id, participant_id):
    context = {}

    user = request.user if request.user.is_authenticated else None

    participant = (
        Participant.objects.annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch(
                "contest",
                queryset=Contest.objects.filter(id=contest_id),
            ),
        )
        .prefetch_related(
            Prefetch("vote_set", queryset=Vote.objects.filter(registered_by=user))
        )
        .get(pk=participant_id)
    )

    context["participant"] = participant
    context["pagination"] = "1"
    context["ongoing"] = (
        participant.contest.start_date <= now()
        and participant.contest.end_date >= now()
        and participant.contest.is_active
    )

    return render(request, "contest/participant/view.html", context=context)


@login_required
def vote(request):
    context = {}

    vote, created = Vote.objects.update_or_create(
        registered_by=request.user,
        participant_id=request.POST.get("participant_id"),
        defaults={"vote": request.POST.get("vote")},
    )

    participant = (
        Participant.objects.annotate(
            rating=Coalesce(
                Sum(
                    Case(
                        When(
                            Q(vote__registered_by__in=F("contest__judges")),
                            then=F("vote__vote") * F("contest__judge_vote_weight"),
                        ),
                        default=F("vote__vote"),
                        output_field=IntegerField(),
                    )
                ),
                0,
            )
        )
        .prefetch_related(
            Prefetch(
                "vote_set",
                queryset=Vote.objects.filter(
                    registered_by=request.user,
                    participant__id=request.POST.get("participant_id"),
                ),
            )
        )
        .get(pk=request.POST.get("participant_id"))
    )
    context["participant"] = participant

    context["ongoing"] = (
        participant.contest.start_date <= now()
        and participant.contest.end_date >= now()
        and participant.contest.is_active
    )

    time.sleep(1)

    return render(request, "contest/participant/_participant.html", context)

contest/templates/contest/contest/list.html
{% extends "imaginaria/base.html" %}
{% load static %}

{% block head %}
    <title>_concursos</title>
    <link href="{% static "contest/css/contest/list.css" %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div id="contests">
        {% for contest in contests %}
            <div class="contest">
                <a href="{% url "contest:contest_view" contest_id=contest.id %}">
                    <header class="contest-header">{{ contest.name }}</header>
                </a>
                <span><b>{% translate "Início" %}:</b> {{ contest.start_date }}</span>
                <br />
                <span><b>{% translate "Fim" %}:</b> {{ contest.end_date }}</span>
                <br />
                <a href="{% url "contest:participant_list" contest_id=contest.id %}">Votar</a>
                {% for participant in participants %}
                    {% if participant.contest == contest %}
                        <div class="participant">
                            {{ participant.name }} | <b>{{ participant.rating_sum }}</b>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="14" fill="var(--main-color)" viewBox="0 0 20 12">
                                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                            </svg>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}

contest/templates/contest/contest/view.html
{% extends "imaginaria/base.html" %}
{% load static %}

{% block head %}
    <link href="{% static "contest/css/contest/view.css" %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="contest">
        <header class="contest-name">{{ contest.name }}
            <a href="{% url "contest:participant_list" contest_id=contest.id %}">Votar</a>
        </header>
        <br />
        <span class="contest-date"><b>Início:</b> {{ contest.start_date }}</span>
        <br />
        <span class="contest-date"><b>Fim:</b> {{ contest.end_date }}</span>
        <hr style="border-top: 2px solid var(--secondary-color); margin-top: 20px">
        <div id="participants">
            {% for participant in participants %}
                <div class="participant">
                    <span class="participant-work">{{ participant.work }} - {{ participant.rating_sum }} 
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="14" fill="var(--main-color)" viewBox="0 0 20 12">
                            <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                        </svg>
                    </span>
                    <br />
                    <span class="participant-name">{{ participant.name }}</span>
                </div>
            {% endfor %}
            </div>
    </div>
{% endblock content %}